DROP DATABASE IF EXISTS tcc;


CREATE DATABASE tcc;

USE tcc;

CREATE TABLE usuario(
id INT(11) AUTO_INCREMENT NOT NULL,
nome VARCHAR(50) NOT NULL,
senha VARCHAR(50) NOT NULL,
email VARCHAR(60) NOT NULL,
telefone VARCHAR(15) NOT NULL,
sexo VARCHAR(15) NOT NULL,
data_nasc DATE NOT NULL,
cidade VARCHAR (45) NOT NULL,
estado VARCHAR(45) NOT NULL,
endereco VARCHAR (45) NOT NULL,

PRIMARY KEY (id));

CREATE TABLE funcionario(
id INT(11) AUTO_INCREMENT NOT NULL,
nome VARCHAR(50) NOT NULL,
senha VARCHAR(50) NOT NULL,
email VARCHAR(60) NOT NULL,
telefone VARCHAR(15) NOT NULL,
sexo VARCHAR(15) NOT NULL,
data_nasc DATE NOT NULL,
cidade VARCHAR (45) NOT NULL,
estado VARCHAR(45) NOT NULL,
endereco VARCHAR (45) NOT NULL,

PRIMARY KEY (id));